name: "Automatic requirements.txt with Python 3.10"
description: "Automatically update the requirements.txt file using the pipreqs. Forked from ryan-rozario/pipreqs-action to use Python 3.10"
author: "Erik Heimdal"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "."

  REQUIREMENT_PATH:
    description: "Folder where requirements.txt has to be saved in"
    required: true
    default: "requirements.txt"

  PROJECT_NAME:
    description: "Name of the project to include in the commit"
    required: true
    default: ""

  COMMIT_MESSAGE:
    description: "Name of the project to include in the commit"
    required: true
    default: "Updated requirements file"


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'code'
  color: 'yellow'
